version: "2"

services:
  web:
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
    container_name: anibal-app.dev
    volumes:
      - .:/go/src/anibal
    working_dir: /go/src/anibal
    command: go run main.go
    ports:
      - "3000:3000" # http
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    build:
      context: .
      dockerfile: .docker/server/mariadb/Dockerfile
    image: my-mysql:1.0
    container_name: database-mysql.dev
    hostname: database-mysql.dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s3nHa
      MYSQL_DATABASE: anibal
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      #- ../../_local_mysql_data:/var/lib/mysql
      #- ./anibaldb.sql:/tmp/anibaldb.sql
      #- ./import.sh:/tmp/import.sh
      - ./mysql_init:/docker-entrypoint-initdb.d